// Catalog screen

export const ADD_TO_CART = 'ADD_TO_CART';
export const INC_COUNT_CART = 'INC_COUNT_CART';
export const DEC_COUNT_CART = 'DEC_COUNT_CART';
export const TOGGLE_NEED_OPEN_CART = 'TOGGLE_NEED_OPEN_CART';
export const TOGGLE_NEED_CLOSE_CART = 'TOGGLE_NEED_CLOSE_CART';
export const SET_PRODUCTS_FETCHING = 'SET_PRODUCTS_FETCHING';
export const SET_TAGS_FETCHING = 'SET_TAGS_FETCHING';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_TAGS = 'SET_TAGS';
export const SELECT_TAG = 'SELECT_TAG';


// Checkout screen


export const SET_USER_NAME = 'SET_NAME';
export const SET_USER_TEL = 'SET_USER_TEL';
export const SET_USER_MAIL = 'SET_USER_MAIL';
export const SET_USER_DELIVERY_ADRESS = 'SET_USER_DELIVERY_ADRESS';
export const SET_USER_DISTRICT = 'SET_USER_DISTRICT';
export const SET_USER_COMMENT = 'SET_USER_COMMENT';
export const SET_USER_PAYMENT = 'SET_USER_PAYMENT';
export const SET_SENDING_ORDER = 'SET_SENDING_ORDER';


// Profile screen

export const SET_IS_SENDING = 'SET_IS_SENDING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_DATA = 'SET_CURRENT_USER_DATA';



